/**
 * @file Grievance.js
 * @description Mongoose schema for Grievance records.
 * The core entity storing description, status, categorization, reporter details, and assignment.
 */

import mongoose from "mongoose";

const grievanceSchema = new mongoose.Schema(
  {
    // Unique human-readable ID (e.g., PGS-2024-X89Z) generated by utility function
    grievanceId: { type: String, required: true, unique: true },

    // Reporter: Optional User ID (null if submitted anonymously)
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: false, 
    },

    // Snapshot of reporter details at creation time (ensures historical accuracy even if profile changes)
    createdBy: {
      name: String,
      email: String,
      primaryContact: String,
    },

    // Category Reference
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
      required: true,
    },

    // Main Content
    title: { type: String, required: true },
    description: { type: String },

    // Attachments (Array of file paths/URLs from S3)
    attachments: [{ type: String }],

    // Current Status Workflow
    status: {
      type: String,
      enum: ["Submitted", "In Review", "Assigned", "In Progress", "Resolved", "Closed", "Rejected"],
      default: "Submitted",
    },

    // Urgency Level
    priority: {
      type: String,
      enum: ["Low", "Medium", "High"],
      default: "Medium",
    },

    // Location of the issue
    location: { type: String },

    // Assigned Official (Staff member responsible for resolution)
    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    // Flag for anonymous submissions
    isAnonymous: { type: Boolean, default: false },
  },
  { timestamps: true }
);

export default mongoose.model("Grievance", grievanceSchema);
